services:
  php-fpm:
    build:
      context: ../
      dockerfile: devops/php-fpm/Dockerfile
      target: dev
    expose:
      - 9000
    volumes:
      - ../:/var/www
    networks:
      - backend
  nginx:
    build:
      context: ../
      dockerfile: devops/nginx/Dockerfile
    volumes:
       - ../public:/var/www/public
       - ../devops/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
