name: "Continuous Integration"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image from Source Code
        uses: docker/build-push-action@v2
        with:
          file: devops/php-fpm/Dockerfile
          target: dev
          build-args: |
            ARG_RUBY_VERSION=${{ env.RUBY_VERSION }}
          context: .
          tags: php-fpm:latest
          outputs: type=docker,dest=/tmp/php-fpm.tar

      - name: Upload docker image
        uses: actions/upload-artifact@v2
        with:
          name: php-fpm
          path: /tmp/php-fpm.tar
          retention-days: 1

  run-phpunit:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpunit-suite: ["Suite1", "Suite2"]
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: php-fpm
          path: /tmp

      - name: Load docker image
        run: docker load -i /tmp/php-fpm.tar

      - name: Run PHPUnit
        run: |
          docker run --rm php-fpm:latest \
            sh -c "vendor/bin/phpunit --testsuite ${{ matrix.phpunit-suite }}"
